// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Transport-level push token type shared across the platform channel.
enum PushTokenType: Int {
  /// Firebase Cloud Messaging token (Android, optionally iOS).
  case fcm = 0
  /// Apple Push Notification service device token (iOS).
  case apns = 1
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PushTokenType(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PushTokenType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host (native) API invoked from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MediquoHostApi {
  /// Initialises the native MediQuo SDK with the partner [apiKey].
  func initialize(apiKey: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Authenticates the pre-registered patient identified by [clientCode] (CPF).
  func authenticate(clientCode: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Presents the native professional-list interface.
  func openProfessionalList(completion: @escaping (Result<Void, Error>) -> Void)
  /// Logs the current patient out of the native SDK.
  func deauthenticate(completion: @escaping (Result<Void, Error>) -> Void)
  /// Registers a push [token] of the given [type] with the native SDK.
  func registerPushToken(token: String, type: PushTokenType, completion: @escaping (Result<Void, Error>) -> Void)
  /// Presents the SDK screen that corresponds to a tapped remote notification.
  ///
  /// [payload] is the notification data (for example
  /// `RemoteMessage.data`). On iOS this routes to the deep-linked screen via
  /// `getSDKViewController(forRemotePush:)`; on Android, where the bundled
  /// messaging service already deep-links taps, it falls back to the
  /// professional list.
  func openFromRemoteNotification(payload: [String: Any?], completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MediquoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MediquoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MediquoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialises the native MediQuo SDK with the partner [apiKey].
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        api.initialize(apiKey: apiKeyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Authenticates the pre-registered patient identified by [clientCode] (CPF).
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientCodeArg = args[0] as! String
        api.authenticate(clientCode: clientCodeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    /// Presents the native professional-list interface.
    let openProfessionalListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.openProfessionalList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openProfessionalListChannel.setMessageHandler { _, reply in
        api.openProfessionalList { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openProfessionalListChannel.setMessageHandler(nil)
    }
    /// Logs the current patient out of the native SDK.
    let deauthenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.deauthenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deauthenticateChannel.setMessageHandler { _, reply in
        api.deauthenticate { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deauthenticateChannel.setMessageHandler(nil)
    }
    /// Registers a push [token] of the given [type] with the native SDK.
    let registerPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.registerPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        let typeArg = args[1] as! PushTokenType
        api.registerPushToken(token: tokenArg, type: typeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPushTokenChannel.setMessageHandler(nil)
    }
    /// Presents the SDK screen that corresponds to a tapped remote notification.
    ///
    /// [payload] is the notification data (for example
    /// `RemoteMessage.data`). On iOS this routes to the deep-linked screen via
    /// `getSDKViewController(forRemotePush:)`; on Android, where the bundled
    /// messaging service already deep-links taps, it falls back to the
    /// professional list.
    let openFromRemoteNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mediquo_flutter.MediquoHostApi.openFromRemoteNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openFromRemoteNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! [String: Any?]
        api.openFromRemoteNotification(payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openFromRemoteNotificationChannel.setMessageHandler(nil)
    }
  }
}
